# Generated by Django 4.2.3 on 2023-10-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(max_length=100)),
                ('Reminder', models.TimeField(auto_now_add=True)),
                ('Date', models.DateField(blank=True)),
            ],
        ),
    ]
