# Generated by Django 4.2.3 on 2023-10-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
